server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:

    compatibility-verifier:
      enabled: false


    gateway:
      routes:

        # RUTA HACIA MS-USUARIOS (puerto 8081)
        - id: ms-usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/api/usuarios/**

        # RUTA HACIA MS-PRODUCTOS (puerto 8082)
        - id: ms-productos
          uri: http://localhost:8082
          predicates:
            - Path=/api/productos/**

        # RUTA HACIA MS-VENTAS (puerto 8083)
        - id: ms-ventas
          uri: http://localhost:8083
          predicates:
            - Path=/api/ventas/**
